(() => {
const {data,el,path,picture,card,badges}=window.Yudum,main=document.getElementById('content'),params=new URLSearchParams(location.search),id=params.get('id')||'collection',query=params.get('search');main.replaceChildren();
const crumb=el('p','breadcrumb');const home=el('a','','Anasayfa');home.href='index.html';crumb.append(home,document.createTextNode(' / '+(query?'Arama':'Keşfet')));main.append(crumb);
function grid(items){const g=el('div','grid');items.forEach(i=>g.append(card(i)));main.append(g);}
function title(text){document.title=text+' | Yudum';main.append(el('h1','',text));}
if(query!==null){title('Arama sonuçları');main.append(el('p','lead','“'+query+'” için sonuçlar'));const all=[...data.recipes,...data.products,...data.expertise,...Object.entries(data.articles).map(([id,a])=>({...a,id}))];const results=all.filter(a=>(a.title+' '+(a.intro||'')+' '+(a.body||'')).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));if(results.length)grid(results);else main.append(el('p','','Bu arama için sonuç bulunamadı.'));return;}
if(id==='expertise'){title('Yağ Uzmanlığımız');grid(data.expertise);return;}
if(id==='collection'){title('Sofranıza ilham veren tarifler.');main.append(el('p','lead','Bir yudum ilham, her gün yeni bir lezzet.'));grid(data.recipes);return;}
if(id==='journal'){title('Her yudumda bir hikâye.');grid(['women','seed','delice','harvest'].map(id=>({...data.articles[id],id})));return;}
const pending={quality:'Üretim Tesislerimiz & Kalite',kvkk:'KVKK Aydınlatma Metni',privacy:'Gizlilik Politikası',cookies:'Çerez Politikası'};
if(pending[id]){title(pending[id]);main.append(el('p','lead','Bu sayfanın içeriği hazırlanıyor.'));return;}
const recipe=data.recipes.find(r=>r.id===id),product=data.products.find(p=>p.id===id),item=recipe||product||data.expertise.find(e=>e.id===id)||data.articles[id];
if(!item){title('Sayfa bulunamadı');main.append(el('p','','Aradığınız içerik bulunamadı. Anasayfadan devam edebilirsiniz.'));return;}
document.title=item.title+' | Yudum';const hero=el('section','detail-hero'+(product||/stage-|ayvalik|Sisesi/.test(item.image)?' product':''));hero.append(picture(item.image,item.title));const copy=el('div');copy.append(el('p','eyebrow',recipe?'İLHAM VEREN TARİFLER':product?'ÜRÜNLER':item.category||'YAĞ UZMANLIĞIMIZ'),el('h1','',item.title));if(item.intro)copy.append(el('p','lead',item.intro));if(recipe)copy.append(badges(recipe));hero.append(copy);main.append(hero);
if(recipe){const facts=el('dl','recipe-facts');[['Hangi Yudum kullanılıyor?',recipe.oil],['Neden bu yağ seçiliyor?',recipe.why],['Hangi pişirme tekniği?',recipe.technique]].forEach(([q,a])=>{const g=el('div');g.append(el('dt','',q),el('dd','',a));facts.append(g);});main.append(facts);if(recipe.body)main.append(el('div','article-body',recipe.body));const body=el('div','recipe-body');[['Malzemeler',recipe.ingredients,'ul'],['Hazırlanışı',recipe.steps,'ol']].forEach(([heading,items,tag])=>{if(!items.length)return;const section=el('section');section.append(el('h2','',heading));const list=el(tag);items.forEach(t=>list.append(el('li','',t)));section.append(list);body.append(section);});main.append(body);}else{main.append(el('div','article-body',item.body||''));if(item.children)grid(item.children.map(id=>data.products.find(p=>p.id===id)).filter(Boolean));if(id==='contact'){const a=el('a','primary','E-posta gönder');a.href='mailto:info@yudum.com.tr';main.append(a);}}
})();
